services:
  docker:
    image: docker:27.3.1-dind
    container_name: circleguard-docker
    privileged: true
    command:
      - dockerd-entrypoint.sh
      - --host=tcp://0.0.0.0:2375
      - --host=unix:///var/run/docker.sock
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - docker_data:/var/lib/docker

  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: circleguard-jenkins
    restart: unless-stopped
    user: root
    depends_on:
      - docker
    ports:
      - '8080:8080'
      - '50000:50000'
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  docker_data:
  jenkins_home:
